### PR TITLE
feat: `/support data-request` command

### LINKED ISSUE #1743: [FEAT] - `/support data-request` command
### What feature would you like to see?

We should add a `/support data-request` command. This command should:

- Should fetch the user's record for each of the user-specific data collections:
  - `activities`
  - `currencies`
  - `emotecounts`
  - `messagecounts`
  - `newlevels`
  - `optouts`
  - `starcounts`
  - `userconfigs`
  - `voters`
- Should check if the user is the **guild owner**, and if so, fetch each of the guild-specific data collections:
  - `histories`
  - `polls`
  - `scheduledevents`
  - `servers`
- Should take all fetched data, compile it into a JSON object, and build that object into a Discord attachment
- Should send the attachment, as well a message content explaining that they should join the support server to request data deletion

### Additional information

The JSON should look something like:

```json
{
  activities: [
  {
    userId: "465650873650118659",
    buttons: 128
  }
 ],
 currencies: {}
}
```

Note that models that have a single unique ID (userId or serverId) will be a single object, whereas those with both a unique userId and serverId will be an array of objects.

### PR DESCRIPTION
**Pull request by helloimalastair**
# Pull Request

*You may ~~fire~~ merge when ready.*

## Description

Implements the `/support data-request` command, which allows users to request data that Becca has stored that pertains to them.

## Related Issue

Closes #1743

## Documentation

For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.
- [x] My contribution DOES require a documentation update. Documented in PR [#717](https://github.com/nhcarrigan/becca-docs/pull/717)

### CODE REVIEW

**Comment by helloimalastair** [comment]
@naomi-lgbt Q about the `schedulevents`collection. An individual `ScheduledEvent` isn't bound to a specific guild, but rather a channel. I could have it loop through every `ScheduledEvent` looking for a match for the current guilds' channels, but that doesn't seem very efficient... Is there some other way you want me to handle this?

**Comment by naomi-lgbt** [comment]
> about the scheduleventscollection. An individual ScheduledEvent isn't bound to a specific guild, but rather a channel. I could have it loop through every ScheduledEvent looking for a match for the current guilds' channels, but that doesn't seem very efficient... Is there some other way you want me to handle this?

Scheduled events *are* tied to members, however. We should be able to query that and return all scheduled events that the user has created.

> I would note too that because we are referring the initial handling of the Interaction, we aren't able to make the response ephemeral, which might have some privacy concerns, depending on what data we may have stored.

There's nothing in the `/support` command that *needs* to be visible, so we could set the original `deferReply()` call to ephemeral.

**Review by naomi-lgbt — APPROVED** [review]
Happy to land this.

Because it's a heavy load on the database, will circle back and determine a rate limiting approach.

**Comment by melody-iuvo** [comment]
## Thank You

Thank you for your continued contribution to our project. We have reviewed your pull request and are happy to accept these changes.

Please continue to watch for issues labelled `help wanted`, as these will be additional opportunities to contribute.

You can also see all open issues [through our contributor tool](https://contribute.naomi.lgbt). Also, feel free to join our [Discord server](https://chat.naomi.lgbt) to chat with us and get notified when new issues are available!

**Pull request merged**
