### PR TITLE
Feat- Message link in logs

### LINKED ISSUE #439: [FEAT]: Message Link in messageUpdated logs
# Feature Request

## Is your feature request related to a problem? Please describe:

Not a very large problem, but it would be a neat feature to have.
The current logs do provide the message content and the Author but in many cases moderators might need additional context regarding the chat, to decide whether some messages were in violation or not.
Scrolling back all the way to the message might be time-consuming and slightly tiresome task for the moderators. 

## Describe the solution you'd like

It would be great, if we use `message.url` to link to the updated message in the log embed.

## Additional context
We could perhaps link to the message in the embed title or add a new field for the URL?
Screenshot of current messageUpdated log embed: 
Screenshot 2020-12-29 at 3 49 53 PM

Would I like to work on this issue:
- [x] yes :)

### PR DESCRIPTION
**Pull request by Vyvy-vi**
# Pull Request

## Description:

This adds a URL of the edited message in the title of the log embed, sent by the bot in the logging channel.
## Related Issue: 
[BeccaLyria#439- "[FEAT]: Message Link in messageUpdated logs"](https://github.com/nhcarrigan/Becca-Lyria/issues/439)

Closes #439 

## Scope:

Did you remember to update the `package.json` version number?

- [ ] Major Version Update: X.\_.\_ (for complete code refactors, or large PRs that adjust most of the codebase)
- [ ] Minor Version Update: \_.X.\_ (for the addition of new commands)
- [x] Patch Version Update: \_.\_.X (for bug fixes _in the code_.)
- [ ] No Version Update: \_.\_.\_ (no version update for additions to tests, documentation, or anything that isn't end-user facing.)

*I am not sure if this counts as a minor update or a patch update(currently I added this as a patch, since there aren't many changes) 😅  
## Documentation:

For _any_ version updates, please verify if the [documentation page](https://beccalyria.nhcarrigan.com) needs an update. If it does, please [create an issue there](https://github.com/nhcarrigan/Becca-Lyria-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [x] My contribution does NOT require a documentation update.
- [ ] My contribution DOES require a documentation update.

## Screenshots:

Screenshot 2020-12-29 at 9 50 43 PM

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
Woah, no check failures :)

**Comment by Vyvy-vi** [comment]
Though, I had a question, should this be added as a field?
(the title link forwards to a browser, rather than highlighting inside discord)

**Comment by nhcarrigan** [comment]
Could be a field, or sent as a separate text message i.e. `View the message: <link>`

**Comment by Vyvy-vi** [comment]
Would multiple edits at the same time affect the second message?
(like two embeds get sent and then 2 links?)

**Comment by nhcarrigan** [comment]
Yes, it would fire on that both times.

**Comment by nhcarrigan** [comment]
> *I am not sure if this counts as a minor update or a patch update(currently I added this as a patch, since there aren't many changes) 😅

Yes, this is a patch version update. Minor version updates are for the addition of new commands. :)

It looks like you bumped the version in the `package-lock.json` - would you bump it in the `package.json` as well?

**Review by nhcarrigan — APPROVED** [review]
LGTM~! 🥳 

Congratulations on your first pull request to this project! We look forward to future contributions!

**Comment by nhcarrigan** [comment]
@all-contributors please add @Vyvy-vi for code

**Pull request merged**
