### PR TITLE
Enhancement: Upload old and new user profile pics to the log

### PR DESCRIPTION
**Pull request by a2937**
# Pull Request

## Description

This pull request's goal is to improve image handling by uploading the old and new avatars as image attachments in the log. It is labelled as a draft so we can discuss ways to improve the implementation. 

## Related Issue

Related to #1579

## Documentation

For _any_ version updates, please verify if the [documentation page](https://docs.beccalyria.com?utm_source=github&utm_medium=pr-template) needs an update. If it does, please [create an issue there](https://github.com/BeccaLyria/discord-documentation/issues/new?assignees=nhcarrigan&labels=%F0%9F%9A%A6+status%3A+awaiting+triage&template=update.md&title=%5BUPDATE%5D) to ensure it is not forgotten.

- [ ] My contribution does NOT require a documentation update.
- [X] My contribution DOES require a documentation update.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
image

Discord is *lightning fast* on purging the avatar from the CDN apparently.
We may not be able to upload the old avatar, but the new one should remain persistent because it becomes a message attachment.

**Comment by a2937** [comment]
Okay how do we save the old then?

**Comment by naomi-lgbt** [comment]
I'm not sure we can - it might be gone before we could even download it.

**Comment by naomi-lgbt** [comment]
I'll ask around and do some digging.

**Comment by melody-iuvo** [comment]
Thank you for your interest in contributing~! With this project in maintenance mode, we will go ahead and close this PR as outdated. If you would like to revisit this, feel free to reach out in our [Discord community](https://chat.nhcarrigan.com)

**Pull request closed without merging**
